"""update_user

Revision ID: 9cbd0634fb12
Revises: 8261511ce222
Create Date: 2020-10-31 17:32:00.679285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbd0634fb12'
down_revision = '8261511ce222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
